# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67fa1154574a48c8835f12e7014e0430e7e8b3fe021d02b5235fa6a68ce39aa958d5a70967963d49aa6d389e609af688091551f78fb40adb14dca27be99fe023

test:
  secret_key_base: b7251b3737171e05f19086145193dbce8bd0a8b1354f8029257b3747182140b3d705c7f1585d26b50bd5bb6a1cf37d23facb5f6ef39d6e79c8ae809c998e9661

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
